### ISSUE TITLE
Path management

### ISSUE THREAD

**Issue by nicholst** [TomMaullin/BLM#62]
I assumed that the README would have instructions on how to modify your PATH variable, or set a BLM environmental variable.  However, it appears that the working directory must be the same as the install directory, which is not desirable.  

Plus, I assume that the temporary files are *also* written out to the install/current directory.

All of these need to be dissociable: 
1.  Location of BLM-py install.  Ideally there would be a *single* directory that needs to be added to a path.  (*Long* *term*, `BLM-py` should be installable with pip, and so you can then automatically assume your executables are on the path... not sure how the Bash scripts play with that.  Long long term, ultimately, need to ditch bash).
1. Location of the configuration file.  Is it right that `blm_cluster.sh` and `blm_serial.py` can be called with a path to (arbitrarily named) `blm_config.yml`. I just want to confirm this.
1. Location of temporary files where output from each run is stored; I assume this is presently the output directory (not BLM-py home), but users may want to have this in some other (e.g. low-latency) temp location.

I've added a small mod in #61 to make `blm_cluster.sh` moveable but I'm not sure what else is needed.

**Comment by TomMaullin** [comment]
In response to (1), I agree, however I am unsure about the pip install as we currently have dependencies on fsl. I'm not sure about converting fully to python when we will always have dependencies on cluster-specific implementations of `qsub` in one form or another.

In response to (2), yes that is true. I haven't documented this as it was a feature I added in quite late for testing purposes but yes that does indeed work.

In response to (3), yes the temporary files are currently made in `{{OUTDIR}}/tmp` where `{{OUTDIR}}` is the users specified output directory. They are deleted once an analysis is run. It would probably not take too much to make it so that the user could specify this.

I have also replied to #61 on the PR.

**Comment by nicholst** [comment]
(1) Python can do system calls so I don't see why bash is so special here, vis-a-vis `qsub` or `fsl_sub`.

(2) Great!

(3) Low priority, but just worth documenting that many temp files are created and later removed.

**Comment by TomMaullin** [comment]
The reason I am unsure here is that we would either have to write a wrapper for `qsub`, which would involve a fair amount of bash, or we would have to use `fsl_sub` which would mean we couldn't install all pre-requisites via a pip install.

But in response to (3), ah yes sure! I will update the documentation during my next PR!

**Comment by nicholst** [comment]
Again, not a priority, but I don't see why bash is so special here.  Yes, there will be either qsub or fsl_sub dependencies, but in the end you're just calling a program and parsing the output... something that either bash or python can do.  

E.g.
```python
import os
output = os.popen("ls").readlines()
print(output)
```

Right?

While we can't eliminate the qsub/fsl_sub dependency, if we stay entirely in the Python ecosystem it allows convenient installation via pip (or however the FSL people recommend if we stay entirely in the fslpython ecosystem.

**Comment by TomMaullin** [comment]
My only concerns are:

 - If we use normal `qsub`, it isn't a case of how we call it that is the issue but rather what to call - `qsub` is different on every cluster and there won't be a simple line we could call from python via subprocesses in python that would work on every system. 

 - If we use `fsl_sub` then `fsl` is a dependency and therefore the users will likely already have `fslpython` somewhere in their system (reinstalling all the requirements would seem unnecessary as the environment we need is already installed somewhere). In addition, doing a pip install would not necessarily install all prerequisites as fsl would not be included.
