### ISSUE TITLE
Design headers

### ISSUE THREAD

**Issue by TomMaullin** [TomMaullin/BLM#70]
As discussed in PR #65 :

The design matrix should, to encourage good practice, show require or at least allow column headers and row ID's.  Either we just _demand_ it, or expect a given behaviour based on extension.  E.g. if "csv" or "tsv", then file _must_ have row header and "column header" (i.e. first row and first column are ignored), while if "dat" then row or column headers are expected and nothing is ignored.   The same pattern could be extended to Y and M files... if "csv" or "tsv" then first row and column are ignored, if "txt" (or, well, anything else) a single column is expected.

**Comment by TomMaullin** [comment]
Hi @nicholst ,

I just wanted to confirm, do we assume a column of headers *as well* as a row of headers in all filetypes? I am a little confused why a single column is expected for `.txt`.

**Comment by nicholst** [comment]
Hi @TomMaullin,

I’m not sure of your question… are you’re asking why allow anything *other* than .csv and .tsv with strict requirements for column headers and row names?  The reason is convenience… while I wish everyone would follow these conventions there are lots of people that would be really annoyed by them… so people can choose.

Does this make sense?

**Comment by TomMaullin** [comment]
Hi @nicholst 

Just to confirm; am I correct in thinking in this issue we want to assume csv's all have a column header but none of them have a row header? Or should it be checking for a column header (and potentially row header?)?

**Comment by nicholst** [comment]
I am all for _strictness_, but with an _out_.

The _strictness_ is that *all* .csv and .tsv's (or whatever you want to support) must have a header row and a "header" column.  (i.e. first row, first column is ignored).

The _out_ is that, for compatibility, if people don't want to deal with this, they use .dat or .txt (or whatever you want to make it) and then it's like what Matlab can read... white space separated numbers, no header columns or rows.

Does this help?  If doing both is a pain then just say... but then I would *only* go for the strict option.

**Comment by TomMaullin** [comment]
I see, this should be possible. I will let you know when it's done.

**Comment by TomMaullin** [comment]
This has now been addressed by PR #81
