### ISSUE TITLE
Update to provide SLURM hooks

### ISSUE THREAD

**Issue by nicholst** [TomMaullin/BLM#86]
The BDI BMRC system is now using SLURM and has just wound down it's SGE system.  Please revise to use SLURM (probably doesn't hurt to leave the SGE hooks commented out) and test to ensure it works with the new system.

**Comment by TomMaullin** [comment]
Right... I will try and fix this at some point by changing to use dask (so we don't have these system specific issues anymore). 

In the meantime, do you know if `fsl_sub' is set up correctly on rescomps SLURM at the moment? If so, we could probably roll back the repo to when we were using `fsl_sub' for now?

**Comment by nicholst** [comment]
I *think* it is... I'll ask.

**Comment by nicholst** [comment]
It does work but you need to activate it with
```
module load fsl_sub_slurm
```

**Comment by TomMaullin** [comment]
The dask update has now been implemented. I will open a separate issue for updating the tests.
